# Generated by Django 5.1.1 on 2024-10-14 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0003_transcription_description_transcription_meta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcription',
            name='model',
        ),
    ]
