# Generated by Django 5.1.1 on 2024-10-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0005_rename_base_segments_transcription_word_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcription',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
