# Generated by Django 5.1.1 on 2024-10-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0006_alter_transcription_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcription',
            name='upload_file',
            field=models.FileField(max_length=255, upload_to='webui/files/uploads/'),
        ),
    ]
