# Generated by Django 5.1.4 on 2025-04-14 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('webui', '0009_alter_segment_transcription_transcriptionstatus'), ('webui', '0010_alter_transcriptionstatus_options'), ('webui', '0011_alter_transcriptionstatus_process_and_more')]

    dependencies = [
        ('webui', '0008_alter_transcription_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='transcription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='webui.transcription'),
        ),
        migrations.CreateModel(
            name='TranscriptionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.IntegerField(choices=[(10, 'downloading'), (20, 'transcribing'), (30, 'diarizing')])),
                ('status', models.IntegerField(choices=[(10, 'pending'), (20, 'processing'), (30, 'completed'), (40, 'failed')], default=10)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(default=None, null=True)),
                ('error_message', models.TextField(default=None, null=True)),
                ('transcription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='webui.transcription')),
            ],
            options={
                'verbose_name_plural': 'transcription statuses',
            },
        ),
    ]
