# Generated by Django 5.1.4 on 2025-04-01 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0008_alter_transcription_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='transcription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='webui.transcription'),
        ),
        migrations.CreateModel(
            name='TranscriptionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.IntegerField(choices=[(10, 'Downloading'), (20, 'Transcribing'), (30, 'Diarizing')])),
                ('status', models.IntegerField(choices=[(10, 'Pending'), (20, 'Processing'), (30, 'Completed'), (40, 'Failed')], default=10)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(default=None, null=True)),
                ('error_message', models.TextField(default=None, null=True)),
                ('transcription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='webui.transcription')),
            ],
        ),
    ]
