# Generated by Django 5.1.4 on 2025-04-01 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0009_alter_segment_transcription_transcriptionstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transcriptionstatus',
            options={'verbose_name_plural': 'transcription statuses'},
        ),
    ]
