# Generated by Django 5.1.4 on 2025-04-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0010_alter_transcriptionstatus_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptionstatus',
            name='process',
            field=models.IntegerField(choices=[(10, 'downloading'), (20, 'transcribing'), (30, 'diarizing')]),
        ),
        migrations.AlterField(
            model_name='transcriptionstatus',
            name='status',
            field=models.IntegerField(choices=[(10, 'pending'), (20, 'processing'), (30, 'completed'), (40, 'failed')], default=10),
        ),
    ]
