# Generated by Django 5.1.4 on 2025-04-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0009_alter_segment_transcription_transcriptionstatus_squashed_0011_alter_transcriptionstatus_process_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptionstatus',
            name='start_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
