"""
Django settings for whisper project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ''

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []

CSRF_TRUSTED_ORIGINS = []


##### START WHISPERSCRIBE SPECIFIC CONFIGURATION #####

# Set Hugging Face token if using diarization.
HUGGING_FACE_TOKEN = ''

# Path to save audio/video files to.
FILE_UPLOAD_PATH = BASE_DIR.joinpath('webui/files/uploads')

# Path to save model caching to.
MODEL_CACHE_PATH = BASE_DIR.joinpath('webui/files/models')

# Should speaker names be uppercase in file downloads?
UPPERCASE_SPEAKER_NAMES = True

# Default max number of characters per segment.
MAX_SEGMENT_LENGTH = 42

# Default max length of segments in seconds.
MAX_SEGMENT_TIME = 7

# The default for the language spoken in the audio. Set to None or '' for auto detection as a default.
WHISPER_LANGUAGE = 'en'

# The list of models available to Whisper (https://huggingface.co/Systran).
WHISPER_MODELS = [
    'tiny',
    'base',
    'small',
    'medium',
    'large-v1',
    'large-v2',
    'large-v3',
]

# The default whisper model to show. Leave empty or set to None for default behavior.
WHISPER_MODEL_DEFAULT = 'base'

# Enable/disable Django-Q.
USE_DJANGO_Q = True

Q_CLUSTER = {
    'name': 'DjangORM',
    'workers': 1,
    'recycle': 2,
    'timeout': 60*60*24,
    'retry': 60*60*25, # https://django-q2.readthedocs.io/en/master/configure.html#retry
    'max_attempts': 1,
    'queue_limit': 100,
    'bulk': 10,
    'orm': 'default'
}

##### END WHISPERSCRIBE SPECIFIC CONFIGURATION #####


CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "django_cache",
    }
}


# Application definition

INSTALLED_APPS = [
    'webui.apps.WebuiConfig',
    'django_cleanup.apps.CleanupConfig',
    'django_q',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
   ('uploads', BASE_DIR / 'webui/files/uploads'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
